
export interface Recipe {
  id: number;
  slug: string;
  title: string;
  category: 'Breakfast' | 'Lunch' | 'Dinner';
  cuisine: string;
  image: string;
  imageHint: string;
  description: string;
  prepTime: string;
  cookTime: string;
  servings: string;
  ingredients: string[];
  instructions: string[];
  nutrition: {
    calories: string;
    protein: string;
    carbohydrates: string;
    fat: string;
  };
}

export const recipes: Recipe[] = [
  // Breakfast
  {
    id: 1,
    slug: 'fluffy-pancakes',
    title: 'Fluffy Everyday Pancakes',
    category: 'Breakfast',
    cuisine: 'American',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?q=80&w=600&h=400&fit=crop',
    imageHint: 'pancakes breakfast',
    description: 'The best and fluffiest pancakes you\'ll ever make. A perfect start to any day.',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '4 people',
    ingredients: [
      '1 1/2 cups all-purpose flour',
      '3 1/2 tsp baking powder',
      '1 tsp salt',
      '1 tbsp white sugar',
      '1 1/4 cups milk',
      '1 egg',
      '3 tbsp butter, melted',
    ],
    instructions: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.',
      'Brown on both sides and serve hot with your favorite toppings.',
    ],
    nutrition: {
      calories: '300 kcal',
      protein: '8g',
      carbohydrates: '40g',
      fat: '12g',
    },
  },
  {
    id: 2,
    slug: 'avocado-toast-with-egg',
    title: 'Avocado Toast with Egg',
    category: 'Breakfast',
    cuisine: 'American',
    image: 'https://images.unsplash.com/photo-1687276287139-88f7333c8ca4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YXZvY2FkbyUyMHRvYXN0JTIwd2l0aCUyMGVnZ3xlbnwwfHwwfHx8Mg%3D%3D',
    imageHint: 'avocado toast',
    description: 'A simple, healthy, and satisfying breakfast. Packed with protein and healthy fats.',
    prepTime: '5 mins',
    cookTime: '5 mins',
    servings: '1 person',
    ingredients: [
      '1 slice of sourdough bread',
      '1/2 ripe avocado',
      '1 large egg',
      '1 tsp olive oil',
      'Red pepper flakes, to taste',
      'Salt and pepper, to taste',
    ],
    instructions: [
      'Toast the slice of bread to your liking.',
      'While bread is toasting, mash the avocado in a small bowl and season with salt and pepper.',
      'Heat olive oil in a non-stick skillet over medium heat. Crack the egg into the skillet and cook to your desired doneness (sunny-side up, over easy, etc.).',
      'Spread the mashed avocado over the toast.',
      'Top with the cooked egg. Sprinkle with red pepper flakes and serve immediately.',
    ],
    nutrition: {
      calories: '350 kcal',
      protein: '15g',
      carbohydrates: '30g',
      fat: '20g',
    },
  },
   {
    id: 3,
    slug: 'berry-smoothie-bowl',
    title: 'Berry Smoothie Bowl',
    category: 'Breakfast',
    cuisine: 'American',
    image: 'https://images.unsplash.com/photo-1727243831783-7ebaafc9ac26?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YmVycnklMjBzbW90aGklMjBib3dsfGVufDB8fDB8fHwy',
    imageHint: 'smoothie bowl',
    description: 'A vibrant and antioxidant-rich smoothie bowl topped with fresh fruits and granola.',
    prepTime: '10 mins',
    cookTime: '0 mins',
    servings: '1 person',
    ingredients: [
      '1 frozen banana',
      '1 cup mixed frozen berries',
      '1/2 cup almond milk',
      '1 tbsp chia seeds',
      'Toppings: fresh berries, sliced banana, granola, coconut flakes',
    ],
    instructions: [
      'In a blender, combine the frozen banana, mixed berries, almond milk, and chia seeds.',
      'Blend on high until smooth and creamy. The consistency should be thick.',
      'Pour the smoothie into a bowl.',
      'Arrange your favorite toppings over the smoothie bowl.',
      'Serve immediately and enjoy with a spoon.',
    ],
    nutrition: {
      calories: '400 kcal',
      protein: '10g',
      carbohydrates: '70g',
      fat: '10g',
    },
  },
  {
    id: 4,
    slug: 'classic-french-toast',
    title: 'Classic French Toast',
    category: 'Breakfast',
    cuisine: 'French',
    image: 'https://images.unsplash.com/photo-1639150362147-00e4cee6b3f5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2xhc3NpYyUyMGZyZW5jaCUyMHRvYXN0fGVufDB8fDB8fHwy',
    imageHint: 'french toast',
    description: 'Golden and custardy French toast, a timeless breakfast favorite for a reason.',
    prepTime: '5 mins',
    cookTime: '10 mins',
    servings: '2 people',
    ingredients: [
      '4 slices of brioche or challah bread',
      '2 large eggs',
      '1/2 cup milk',
      '1 tsp vanilla extract',
      '1/2 tsp cinnamon',
      '2 tbsp butter',
      'Maple syrup and fresh fruit for serving',
    ],
    instructions: [
      'In a shallow dish, whisk together eggs, milk, vanilla extract, and cinnamon.',
      'Melt butter in a large skillet over medium heat.',
      'Dip each slice of bread into the egg mixture, allowing it to soak for about 20 seconds per side.',
      'Place the soaked bread onto the hot skillet and cook for 2-3 minutes per side, until golden brown.',
      'Serve immediately with maple syrup and fresh fruit.',
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '15g',
      carbohydrates: '50g',
      fat: '20g',
    },
  },
  {
    id: 5,
    slug: 'hearty-breakfast-burrito',
    title: 'Hearty Breakfast Burrito',
    category: 'Breakfast',
    cuisine: 'Mexican',
    image: 'https://images.unsplash.com/photo-1563502882399-3f4153513364?q=80&w=600&h=400&fit=crop',
    imageHint: 'breakfast burrito',
    description: 'A filling and customizable breakfast burrito to keep you energized all morning.',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '2 people',
    ingredients: [
      '2 large flour tortillas',
      '4 large eggs, scrambled',
      '1/2 cup cooked black beans, warmed',
      '1/2 cup shredded cheddar cheese',
      '1/4 cup salsa',
      'Optional: cooked sausage or bacon, avocado',
    ],
    instructions: [
      'Warm the tortillas in a dry skillet or microwave until pliable.',
      'Lay a tortilla flat and layer half of the scrambled eggs, black beans, and cheese down the center.',
      'Top with salsa and any other optional fillings.',
      'Fold in the sides of the tortilla, then tightly roll it up from the bottom.',
      'You can either serve immediately or place the burrito seam-side down on a hot skillet to toast for a minute per side.',
      'Repeat with the second tortilla.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '30g',
      carbohydrates: '50g',
      fat: '25g',
    },
  },
  // Lunch
  {
    id: 6,
    slug: 'vibrant-quinoa-salad',
    title: 'Vibrant Quinoa Salad',
    category: 'Lunch',
    cuisine: 'Mediterranean',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=600&h=400&fit=crop',
    imageHint: 'quinoa salad',
    description: 'A colorful and nutrient-packed quinoa salad with a zesty lemon vinaigrette.',
    prepTime: '15 mins',
    cookTime: '20 mins',
    servings: '4 people',
    ingredients: [
      '1 cup quinoa, rinsed',
      '2 cups water or vegetable broth',
      '1 can (15-ounce) chickpeas, rinsed and drained',
      '1 cup chopped cucumber',
      '1 cup halved cherry tomatoes',
      '1/2 cup chopped red onion',
      '1/4 cup chopped fresh parsley',
      'For the Vinaigrette:',
      '1/4 cup olive oil',
      '1/4 cup lemon juice',
      '1 tsp Dijon mustard',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Cook quinoa according to package directions using water or broth. Fluff with a fork and let cool.',
      'In a large bowl, combine the cooled quinoa, chickpeas, cucumber, cherry tomatoes, red onion, and parsley.',
      'In a small bowl, whisk together the olive oil, lemon juice, Dijon mustard, salt, and pepper.',
      'Pour the vinaigrette over the salad and toss to combine.',
      'Serve immediately or chill for later. It\'s even better the next day!',
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '15g',
      carbohydrates: '60g',
      fat: '18g',
    },
  },
  {
    id: 7,
    slug: 'caprese-sandwich',
    title: 'Gourmet Caprese Sandwich',
    category: 'Lunch',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1528738432938-23c3b0d2a849?q=80&w=600&h=400&fit=crop',
    imageHint: 'caprese sandwich',
    description: 'A simple yet elegant sandwich with fresh mozzarella, ripe tomatoes, and basil.',
    prepTime: '10 mins',
    cookTime: '5 mins',
    servings: '1 person',
    ingredients: [
        '2 slices ciabatta or focaccia bread',
        '1 tbsp pesto',
        '1 large ripe tomato, sliced',
        '4 oz fresh mozzarella, sliced',
        'Handful of fresh basil leaves',
        '1 tbsp balsamic glaze',
        '1 tsp olive oil'
    ],
    instructions: [
        'Slice the bread and lightly toast or grill it.',
        'Spread pesto on the inside of both slices of bread.',
        'Layer the tomato slices, mozzarella slices, and fresh basil leaves on the bottom slice.',
        'Drizzle with olive oil and balsamic glaze.',
        'Place the top slice of bread on, press gently, and serve immediately.'
    ],
    nutrition: {
      calories: '500 kcal',
      protein: '20g',
      carbohydrates: '45g',
      fat: '28g',
    },
  },
  {
    id: 8,
    slug: 'chicken-caesar-wrap',
    title: 'Quick Chicken Caesar Wrap',
    category: 'Lunch',
    cuisine: 'American',
    image: 'https://images.unsplash.com/photo-1598373182133-52452f7691ef?q=80&w=600&h=400&fit=crop',
    imageHint: 'chicken wrap',
    description: 'A classic salad turned into a convenient and delicious wrap for an easy lunch.',
    prepTime: '15 mins',
    cookTime: '0 mins',
    servings: '2 people',
    ingredients: [
        '2 large flour tortillas',
        '2 cups chopped romaine lettuce',
        '1 cup cooked, shredded chicken',
        '1/4 cup Caesar dressing',
        '2 tbsp grated Parmesan cheese',
        '1/4 cup croutons'
    ],
    instructions: [
        'In a medium bowl, toss the romaine lettuce, shredded chicken, Caesar dressing, and Parmesan cheese.',
        'Warm the tortillas slightly to make them more pliable.',
        'Spoon half of the salad mixture onto the center of each tortilla.',
        'Sprinkle croutons over the salad.',
        'Fold in the sides and roll up the wraps tightly.',
        'Slice in half and serve.'
    ],
    nutrition: {
      calories: '480 kcal',
      protein: '25g',
      carbohydrates: '40g',
      fat: '25g',
    },
  },
  {
    id: 9,
    slug: 'creamy-lentil-soup',
    title: 'Creamy Red Lentil Soup',
    category: 'Lunch',
    cuisine: 'Middle Eastern',
    image: 'https://images.unsplash.com/photo-1620405230434-42f7035676b7?q=80&w=600&h=400&fit=crop',
    imageHint: 'lentil soup',
    description: 'A comforting and hearty soup that is surprisingly easy to make and full of flavor.',
    prepTime: '10 mins',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '1 tbsp olive oil',
      '1 onion, chopped',
      '2 carrots, chopped',
      '2 cloves garlic, minced',
      '1 cup red lentils, rinsed',
      '4 cups vegetable broth',
      '1 tsp cumin',
      '1/2 tsp turmeric',
      'Juice of 1/2 lemon',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Heat olive oil in a large pot or Dutch oven over medium heat. Add onion and carrots and cook until softened, about 5 minutes.',
      'Add garlic and cook for another minute until fragrant.',
      'Stir in the red lentils, vegetable broth, cumin, and turmeric.',
      'Bring to a boil, then reduce heat and simmer for 20-25 minutes, or until lentils are tender.',
      'For a creamy texture, use an immersion blender to partially or fully blend the soup.',
      'Stir in the lemon juice and season with salt and pepper.',
      'Serve hot, garnished with fresh parsley if desired.'
    ],
    nutrition: {
      calories: '300 kcal',
      protein: '18g',
      carbohydrates: '50g',
      fat: '4g',
    },
  },
  {
    id: 10,
    slug: 'spicy-tuna-stuffed-avocado',
    title: 'Spicy Tuna Stuffed Avocado',
    category: 'Lunch',
    cuisine: 'American',
    image: 'https://images.unsplash.com/photo-1592404052368-a46945ea4a61?q=80&w=600&h=400&fit=crop',
    imageHint: 'stuffed avocado',
    description: 'A low-carb, high-protein lunch that is packed with flavor and healthy fats.',
    prepTime: '10 mins',
    cookTime: '0 mins',
    servings: '1 person',
    ingredients: [
      '1 ripe avocado',
      '1 can (5-ounce) tuna, drained',
      '2 tbsp mayonnaise or Greek yogurt',
      '1 tsp sriracha, or to taste',
      '1 tbsp chopped green onion',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Slice the avocado in half and remove the pit.',
      'In a small bowl, mix together the drained tuna, mayonnaise, sriracha, and green onion.',
      'Season the tuna mixture with salt and pepper.',
      'Spoon the tuna salad into the avocado halves.',
      'Garnish with extra green onion and serve immediately.'
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '30g',
      carbohydrates: '15g',
      fat: '32g',
    },
  },
   {
    id: 18,
    slug: 'greek-salad-with-grilled-chicken',
    title: 'Greek Salad with Grilled Chicken',
    category: 'Lunch',
    cuisine: 'Greek',
    image: 'https://images.unsplash.com/photo-1551248429-4097401297b8?q=80&w=600&h=400&fit=crop',
    imageHint: 'greek salad',
    description: 'A fresh and vibrant Greek salad topped with tender grilled chicken, perfect for a light and healthy lunch.',
    prepTime: '20 mins',
    cookTime: '15 mins',
    servings: '2 people',
    ingredients: [
      '1 lb chicken breast, boneless and skinless',
      '1 tbsp olive oil',
      '1 tsp dried oregano',
      'Salt and pepper to taste',
      '1 head of romaine lettuce, chopped',
      '1 cucumber, diced',
      '1 cup cherry tomatoes, halved',
      '1/2 red onion, thinly sliced',
      '1/2 cup Kalamata olives',
      '4 oz feta cheese, crumbled',
      'For the Dressing:',
      '1/4 cup extra virgin olive oil',
      '2 tbsp red wine vinegar',
      '1 tsp Dijon mustard',
      '1/2 tsp dried oregano',
    ],
    instructions: [
      'Season chicken breasts with olive oil, oregano, salt, and pepper.',
      'Grill or pan-sear the chicken until cooked through, about 6-8 minutes per side. Let it rest, then slice.',
      'In a large bowl, combine lettuce, cucumber, tomatoes, red onion, and olives.',
      'In a small jar, shake together all dressing ingredients until well combined.',
      'Add the sliced chicken and feta cheese to the salad bowl.',
      'Drizzle with dressing, toss gently, and serve immediately.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '45g',
      carbohydrates: '15g',
      fat: '35g',
    }
  },
  {
    id: 19,
    slug: 'thai-chicken-satay-wraps',
    title: 'Thai Chicken Satay Wraps',
    category: 'Lunch',
    cuisine: 'Thai',
    image: 'https://images.unsplash.com/photo-1625109419231-739c9f4d6e6a?q=80&w=600&h=400&fit=crop',
    imageHint: 'chicken satay',
    description: 'Deliciously grilled chicken satay skewers served in a wrap with a creamy peanut sauce.',
    prepTime: '25 mins (plus marination)',
    cookTime: '10 mins',
    servings: '2 people',
    ingredients: [
      '1 lb chicken tenders',
      '2 large flour tortillas or flatbreads',
      '1/2 cup shredded carrots',
      '1/2 cup sliced cucumber',
      'Fresh cilantro sprigs',
      'For the Marinade:',
      '1/4 cup coconut milk',
      '1 tbsp soy sauce',
      '1 tbsp honey or brown sugar',
      '1 tsp turmeric',
      '1 tsp ground coriander',
      '2 cloves garlic, minced',
      'For the Peanut Sauce:',
      '1/2 cup creamy peanut butter',
      '1/4 cup warm water',
      '2 tbsp soy sauce',
      '1 tbsp lime juice',
      '1 tsp sriracha (optional)',
    ],
    instructions: [
      'In a bowl, mix all marinade ingredients. Add chicken tenders and marinate for at least 20 minutes.',
      'While chicken marinates, whisk together all peanut sauce ingredients until smooth. Add more water if needed to reach desired consistency.',
      'Thread chicken onto skewers if using. Grill or pan-fry over medium-high heat for 3-4 minutes per side, until cooked through.',
      'Warm the tortillas. Spread a generous amount of peanut sauce on each.',
      'Place the cooked chicken down the center, top with shredded carrots, cucumber, and cilantro.',
      'Roll up the wraps tightly and serve with extra peanut sauce for dipping.',
    ],
    nutrition: {
      calories: '650 kcal',
      protein: '40g',
      carbohydrates: '50g',
      fat: '35g',
    }
  },
  // Dinner
  {
    id: 11,
    slug: 'creamy-tomato-pasta',
    title: 'Ultimate Creamy Tomato Pasta',
    category: 'Dinner',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1598866594240-a3b5a9502621?q=80&w=600&h=400&fit=crop',
    imageHint: 'creamy pasta',
    description: "A rich and decadent creamy tomato pasta that comes together in under 30 minutes. Perfect for a busy weeknight.",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: "4 people",
    ingredients: [
      "1 lb (450g) rigatoni",
      "2 tbsp olive oil",
      "1 medium yellow onion, chopped",
      "4 cloves garlic, minced",
      "1 (28-ounce) can crushed tomatoes",
      "1/2 cup heavy cream",
      "1/2 cup grated Parmesan cheese",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
      "1/4 cup fresh basil, chopped",
    ],
    instructions: [
      "Cook pasta according to package directions. Reserve 1 cup pasta water.",
      "Heat olive oil in a large skillet. Add onion and cook until soft.",
      "Add garlic and cook for 1 minute. Add crushed tomatoes and oregano. Simmer for 10 minutes.",
      "Reduce heat. Stir in heavy cream and Parmesan cheese until smooth.",
      "Add cooked pasta to the sauce, adding pasta water if too thick.",
      "Stir in fresh basil and serve immediately.",
    ],
    nutrition: {
      calories: "650 kcal",
      protein: "25g",
      carbohydrates: "80g",
      fat: "28g",
    },
  },
  {
    id: 12,
    slug: 'lemon-herb-roast-chicken',
    title: 'Lemon Herb Roast Chicken',
    category: 'Dinner',
    cuisine: 'French',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=600&h=400&fit=crop',
    imageHint: 'roast chicken',
    description: 'A juicy, flavorful roast chicken that is impressive enough for guests but easy enough for a weeknight.',
    prepTime: '15 mins',
    cookTime: '1 hr 15 mins',
    servings: '4 people',
    ingredients: [
      '1 (3-4 lb) whole chicken',
      '1 lemon, halved',
      '1 head of garlic, cut in half crosswise',
      'Few sprigs of fresh rosemary and thyme',
      '2 tbsp olive oil',
      'Salt and freshly ground black pepper',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Pat the chicken dry with paper towels. Rub it all over with olive oil and season generously with salt and pepper.',
      'Stuff the cavity of the chicken with the lemon halves, garlic, and fresh herbs.',
      'Place the chicken in a roasting pan or large oven-safe skillet.',
      'Roast for 1 hour and 15 minutes, or until the juices run clear when a thigh is pierced.',
      'Let the chicken rest for 10-15 minutes before carving. Serve with pan juices.',
    ],
    nutrition: {
      calories: '700 kcal',
      protein: '70g',
      carbohydrates: '5g',
      fat: '45g',
    },
  },
  {
    id: 13,
    slug: 'black-bean-burgers',
    title: 'Best-Ever Black Bean Burgers',
    category: 'Dinner',
    cuisine: 'American',
    image: 'https://images.unsplash.com/photo-1582196016395-2655a9c35452?q=80&w=600&h=400&fit=crop',
    imageHint: 'bean burger',
    description: 'Hearty and flavorful homemade black bean burgers that even meat-eaters will love.',
    prepTime: '20 mins',
    cookTime: '10 mins',
    servings: '4 burgers',
    ingredients: [
      '1 can (15-ounce) black beans, rinsed and patted dry',
      '1/2 green bell pepper, chopped',
      '1/2 onion, chopped',
      '2 cloves garlic',
      '1 egg',
      '1 tbsp chili powder',
      '1 tbsp cumin',
      '1/2 cup bread crumbs',
      '4 hamburger buns and your favorite toppings',
    ],
    instructions: [
      'In a food processor, combine bell pepper, onion, and garlic. Pulse until finely chopped.',
      'Add black beans, egg, chili powder, and cumin. Pulse until combined but still chunky.',
      'Transfer mixture to a bowl and stir in bread crumbs. Let sit for 5 minutes.',
      'Divide mixture into 4 equal portions and shape into patties.',
      'Heat a lightly oiled skillet over medium heat. Cook burgers for 5-7 minutes per side, until browned and firm.',
      'Serve on buns with your favorite toppings like lettuce, tomato, and avocado.',
    ],
    nutrition: {
      calories: '400 kcal',
      protein: '20g',
      carbohydrates: '60g',
      fat: '10g',
    },
  },
  {
    id: 14,
    slug: 'sheet-pan-salmon-and-veggies',
    title: 'Sheet Pan Salmon & Veggies',
    category: 'Dinner',
    cuisine: 'Mediterranean',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&h=400&fit=crop',
    imageHint: 'salmon veggies',
    description: 'A healthy, delicious, and incredibly easy one-pan dinner for minimal cleanup.',
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: '2 people',
    ingredients: [
      '2 (6-ounce) salmon fillets',
      '1 lb asparagus, trimmed',
      '1 pint cherry tomatoes',
      '2 tbsp olive oil',
      '1 tsp dried herbs (like oregano or Italian seasoning)',
      'Salt and pepper to taste',
      'Lemon wedges for serving',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'On a large baking sheet, toss the asparagus and cherry tomatoes with 1 tbsp of olive oil, dried herbs, salt, and pepper.',
      'Roast the vegetables for 10 minutes.',
      'While vegetables roast, pat the salmon fillets dry and rub with the remaining 1 tbsp of olive oil. Season with salt and pepper.',
      'Remove the baking sheet from the oven, push the vegetables to the sides, and place the salmon in the center.',
      'Return to the oven and bake for another 10-12 minutes, or until the salmon is cooked through.',
      'Serve immediately with fresh lemon wedges.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '40g',
      carbohydrates: '20g',
      fat: '35g',
    },
  },
  {
    id: 15,
    slug: 'easy-beef-stir-fry',
    title: 'Easy Beef Stir-Fry',
    category: 'Dinner',
    cuisine: 'Asian',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b70a6?q=80&w=600&h=400&fit=crop',
    imageHint: 'beef stirfry',
    description: 'A quick and easy beef stir-fry that\'s better than takeout and ready in 30 minutes.',
    prepTime: '15 mins',
    cookTime: '15 mins',
    servings: '4 people',
    ingredients: [
      '1 lb flank steak, thinly sliced against the grain',
      '1 tbsp cornstarch',
      '2 tbsp soy sauce',
      '1 tbsp sesame oil',
      '1 head of broccoli, cut into florets',
      '1 red bell pepper, sliced',
      '4 cloves garlic, minced',
      '1 tbsp grated ginger',
      'Cooked rice for serving',
    ],
    instructions: [
      'In a bowl, toss the sliced beef with cornstarch.',
      'In a separate small bowl, whisk together soy sauce and sesame oil for the sauce.',
      'Heat 1 tbsp of vegetable oil in a large skillet or wok over high heat. Add beef and cook until browned. Remove from skillet.',
      'Add a little more oil to the skillet. Add broccoli and bell pepper and stir-fry for 3-4 minutes.',
      'Add garlic and ginger and cook for 1 more minute.',
      'Return the beef to the skillet. Pour the sauce over everything and toss to combine until the sauce has thickened.',
      'Serve immediately over cooked rice.',
    ],
    nutrition: {
      calories: '500 kcal',
      protein: '35g',
      carbohydrates: '40g',
      fat: '22g',
    },
  },
  {
    id: 16,
    slug: 'chicken-tikka-masala',
    title: 'Chicken Tikka Masala',
    category: 'Dinner',
    cuisine: 'Indian',
    image: 'https://images.unsplash.com/photo-1628294896516-344152572ee8?q=80&w=600&h=400&fit=crop',
    imageHint: 'chicken curry',
    description: 'A rich and creamy curry that is a staple in Indian cuisine. Perfect with naan or rice.',
    prepTime: '20 mins (plus marination)',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '1.5 lbs boneless, skinless chicken breasts, cut into 1-inch cubes',
      '1 cup plain yogurt',
      '1 tbsp lemon juice',
      '2 tsp ground cumin',
      '2 tsp paprika',
      '1 tsp turmeric',
      '1 tsp garam masala',
      '1 tbsp minced ginger',
      '2 cloves garlic, minced',
      '1 tbsp vegetable oil',
      '1 large onion, chopped',
      '1 (15-ounce) can tomato sauce',
      '1 cup heavy cream',
      'Fresh cilantro for garnish',
    ],
    instructions: [
      'In a bowl, combine yogurt, lemon juice, cumin, paprika, turmeric, garam masala, ginger, and garlic. Add chicken and toss to coat. Marinate for at least 1 hour.',
      'Heat oil in a large skillet over medium-high heat. Add chicken and cook until browned on all sides. Remove chicken from skillet.',
      'Add onion to the skillet and cook until soft. Stir in tomato sauce and cook for 5 minutes.',
      'Stir in heavy cream and bring to a simmer. Return chicken to the skillet.',
      'Simmer for 10-15 minutes until chicken is cooked through and sauce has thickened.',
      'Garnish with cilantro and serve with rice or naan bread.',
    ],
    nutrition: {
      calories: '600 kcal',
      protein: '50g',
      carbohydrates: '20g',
      fat: '38g',
    },
  },
  {
    id: 17,
    slug: 'classic-beef-tacos',
    title: 'Classic Beef Tacos',
    category: 'Dinner',
    cuisine: 'Mexican',
    image: 'https://images.unsplash.com/photo-1565299712547-418a1a399462?q=80&w=600&h=400&fit=crop',
    imageHint: 'beef tacos',
    description: 'A family-favorite taco recipe that is quick, easy, and endlessly customizable.',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '4 people',
    ingredients: [
      '1 lb ground beef',
      '1 packet taco seasoning',
      '3/4 cup water',
      '12 hard taco shells or small flour tortillas',
      'Toppings: shredded lettuce, diced tomatoes, shredded cheddar cheese, salsa, sour cream'
    ],
    instructions: [
      'In a large skillet, cook ground beef over medium-high heat until no longer pink. Drain excess fat.',
      'Stir in taco seasoning and water. Bring to a simmer and cook for 5-7 minutes, until the sauce has thickened.',
      'Warm taco shells or tortillas according to package directions.',
      'Spoon the beef mixture into the shells.',
      'Set up a topping bar with lettuce, tomatoes, cheese, salsa, and sour cream, and let everyone build their own tacos.',
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '25g',
      carbohydrates: '30g',
      fat: '25g',
    },
  },
  {
    id: 20,
    slug: 'thai-green-curry-chicken',
    title: 'Authentic Thai Green Curry',
    category: 'Dinner',
    cuisine: 'Thai',
    image: 'https://images.unsplash.com/photo-1572455014639-9d96952d921b?q=80&w=600&h=400&fit=crop',
    imageHint: 'thai curry',
    description: 'A fragrant and spicy Thai green curry with tender chicken and vegetables, all simmered in coconut milk.',
    prepTime: '15 mins',
    cookTime: '25 mins',
    servings: '4 people',
    ingredients: [
      '1.5 lbs chicken breast, cubed',
      '1 tbsp coconut oil',
      '1/4 cup green curry paste',
      '1 can (13.5-ounce) full-fat coconut milk',
      '1 cup chicken broth',
      '1 red bell pepper, sliced',
      '1 cup snow peas',
      '1 tbsp fish sauce',
      '1 tsp sugar',
      'Fresh basil leaves for garnish',
      'Jasmine rice for serving',
    ],
    instructions: [
      'Heat coconut oil in a large pot or skillet over medium-high heat.',
      'Add the green curry paste and cook for 1 minute until fragrant.',
      'Add the cubed chicken and cook until lightly browned.',
      'Stir in the coconut milk and chicken broth. Bring to a simmer.',
      'Reduce heat and cook for 15 minutes, stirring occasionally.',
      'Add the bell pepper and snow peas and cook for another 5-7 minutes, until vegetables are tender-crisp.',
      'Stir in the fish sauce and sugar.',
      'Serve hot over jasmine rice, garnished with fresh basil.',
    ],
    nutrition: {
      calories: '580 kcal',
      protein: '45g',
      carbohydrates: '25g',
      fat: '35g',
    }
  },
  {
    id: 21,
    slug: 'spanish-garlic-shrimp',
    title: 'Spanish Garlic Shrimp (Gambas al Ajillo)',
    category: 'Dinner',
    cuisine: 'Spanish',
    image: 'https://images.unsplash.com/photo-1625944112193-8a04b3975a5e?q=80&w=600&h=400&fit=crop',
    imageHint: 'garlic shrimp',
    description: 'A classic Spanish tapa of shrimp sizzled in olive oil with lots of garlic and a touch of chili.',
    prepTime: '10 mins',
    cookTime: '10 mins',
    servings: '4 people (as a tapa)',
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '1/2 cup extra virgin olive oil',
      '10-12 cloves garlic, thinly sliced',
      '1/2 tsp red pepper flakes',
      '2 tbsp dry sherry or white wine',
      '2 tbsp chopped fresh parsley',
      'Crusty bread for serving',
    ],
    instructions: [
      'Heat olive oil in a large skillet or cazuela over medium heat.',
      'Add the sliced garlic and red pepper flakes. Cook until the garlic is golden and fragrant, but not burnt (about 1-2 minutes).',
      'Turn the heat up to high, add the shrimp to the skillet in a single layer.',
      'Cook the shrimp for 1-2 minutes per side, until they turn pink and opaque.',
      'Pour in the sherry, and let it bubble for 30 seconds, scraping up any browned bits.',
      'Remove from heat, stir in the parsley, and season with salt.',
      'Serve immediately in the skillet with crusty bread for dipping in the garlic oil.',
    ],
    nutrition: {
      calories: '350 kcal',
      protein: '22g',
      carbohydrates: '5g',
      fat: '25g',
    }
  },
  {
    id: 22,
    slug: 'classic-beef-lasagna',
    title: 'Classic Beef Lasagna',
    category: 'Dinner',
    cuisine: 'Italian',
    image: 'https://images.unsplash.com/photo-1574894709920-31b2e3d5b706?q=80&w=600&h=400&fit=crop',
    imageHint: 'lasagna dinner',
    description: 'Layers of rich meat sauce, creamy béchamel, and tender pasta, baked to golden perfection.',
    prepTime: '30 mins',
    cookTime: '1 hr',
    servings: '6-8 people',
    ingredients: [
      '1 lb ground beef',
      '1 onion, chopped',
      '2 cloves garlic, minced',
      '1 (28-ounce) can crushed tomatoes',
      '2 (6-ounce) cans tomato paste',
      '1/2 cup water',
      '2 tsp sugar',
      '1.5 tsp dried basil',
      '1/2 tsp fennel seeds',
      '1 tsp salt',
      '1/4 tsp black pepper',
      '12 lasagna noodles, cooked',
      '16 oz ricotta cheese',
      '1 egg',
      '1/2 cup grated Parmesan cheese',
      '1 lb mozzarella cheese, sliced',
    ],
    instructions: [
      'In a Dutch oven, cook beef, onion, and garlic over medium heat until browned. Drain fat.',
      'Stir in crushed tomatoes, tomato paste, water, sugar, basil, fennel, salt, and pepper. Bring to a boil, reduce heat, and simmer for 1 hour, stirring occasionally.',
      'Preheat oven to 375°F (190°C).',
      'In a bowl, mix ricotta cheese, egg, and half of the Parmesan cheese.',
      'To assemble, spread 1.5 cups of meat sauce in the bottom of a 9x13 inch baking dish.',
      'Arrange noodles over meat sauce. Spread with half of the ricotta mixture. Top with a third of the mozzarella slices.',
      'Repeat layers. Top with remaining meat sauce and mozzarella and Parmesan cheese.',
      'Bake for 25-30 minutes or until bubbly. Let stand for 10 minutes before serving.',
    ],
    nutrition: {
      calories: '750 kcal',
      protein: '45g',
      carbohydrates: '60g',
      fat: '38g',
    }
  }
];

export const getRecipeBySlug = (slug: string) => {
  return recipes.find(recipe => recipe.slug === slug);
}
