
export interface Recipe {
  id: number;
  slug: string;
  title: string;
  category: 'Breakfast' | 'Lunch' | 'Dinner';
  cuisine: string;
  diet: 'veg' | 'non-veg';
  image: string;
  imageHint: string;
  description: string;
  prepTime: string;
  cookTime: string;
  servings: string;
  ingredients: string[];
  instructions: string[];
  nutrition: {
    calories: string;
    protein: string;
    carbohydrates: string;
    fat: string;
    fiber: string;
    sugar: string;
    sodium: string;
  };
}

export const recipes: Recipe[] = [
  // Breakfast
  {
    id: 1,
    slug: 'fluffy-pancakes',
    title: 'Fluffy Everyday Pancakes',
    category: 'Breakfast',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/fluffy-pancakes.jpg',
    imageHint: 'pancakes breakfast',
    description: 'The best and fluffiest pancakes you\'ll ever make. A perfect start to any day.',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '4 people',
    ingredients: [
      '1 1/2 cups all-purpose flour',
      '3 1/2 tsp baking powder',
      '1 tsp salt',
      '1 tbsp white sugar',
      '1 1/4 cups milk',
      '1 egg',
      '3 tbsp butter, melted',
    ],
    instructions: [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake.',
      'Brown on both sides and serve hot with your favorite toppings.',
    ],
    nutrition: {
      calories: '300 kcal',
      protein: '8g',
      carbohydrates: '40g',
      fat: '12g',
      fiber: '2g',
      sugar: '7g',
      sodium: '450mg',
    },
  },
  {
    id: 2,
    slug: 'avocado-toast-with-egg',
    title: 'Avocado Toast with Egg',
    category: 'Breakfast',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/avocado-toast-with-egg.jpg',
    imageHint: 'avocado toast',
    description: 'A simple, healthy, and satisfying breakfast. Packed with protein and healthy fats.',
    prepTime: '5 mins',
    cookTime: '5 mins',
    servings: '1 person',
    ingredients: [
      '1 slice of sourdough bread',
      '1/2 ripe avocado',
      '1 large egg',
      '1 tsp olive oil',
      'Red pepper flakes, to taste',
      'Salt and pepper, to taste',
    ],
    instructions: [
      'Toast the slice of bread to your liking.',
      'While bread is toasting, mash the avocado in a small bowl and season with salt and pepper.',
      'Heat olive oil in a non-stick skillet over medium heat. Crack the egg into the skillet and cook to your desired doneness (sunny-side up, over easy, etc.).',
      'Spread the mashed avocado over the toast.',
      'Top with the cooked egg. Sprinkle with red pepper flakes and serve immediately.',
    ],
    nutrition: {
      calories: '350 kcal',
      protein: '15g',
      carbohydrates: '30g',
      fat: '20g',
      fiber: '10g',
      sugar: '2g',
      sodium: '300mg',
    },
  },
   {
    id: 3,
    slug: 'berry-smoothie-bowl',
    title: 'Berry Smoothie Bowl',
    category: 'Breakfast',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/berry-smoothie-bowl.jpg',
    imageHint: 'smoothie bowl',
    description: 'A vibrant and antioxidant-rich smoothie bowl topped with fresh fruits and granola.',
    prepTime: '10 mins',
    cookTime: '0 mins',
    servings: '1 person',
    ingredients: [
      '1 frozen banana',
      '1 cup mixed frozen berries',
      '1/2 cup almond milk',
      '1 tbsp chia seeds',
      'Toppings: fresh berries, sliced banana, granola, coconut flakes',
    ],
    instructions: [
      'In a blender, combine the frozen banana, mixed berries, almond milk, and chia seeds.',
      'Blend on high until smooth and creamy. The consistency should be thick.',
      'Pour the smoothie into a bowl.',
      'Arrange your favorite toppings over the smoothie bowl.',
      'Serve immediately and enjoy with a spoon.',
    ],
    nutrition: {
      calories: '400 kcal',
      protein: '10g',
      carbohydrates: '70g',
      fat: '10g',
      fiber: '12g',
      sugar: '35g',
      sodium: '50mg',
    },
  },
  {
    id: 4,
    slug: 'classic-french-toast',
    title: 'Classic French Toast',
    category: 'Breakfast',
    cuisine: 'French',
    diet: 'veg',
    image: '/images/recipes/classic-french-toast.jpg',
    imageHint: 'french toast',
    description: 'Golden and custardy French toast, a timeless breakfast favorite for a reason.',
    prepTime: '5 mins',
    cookTime: '10 mins',
    servings: '2 people',
    ingredients: [
      '4 slices of brioche or challah bread',
      '2 large eggs',
      '1/2 cup milk',
      '1 tsp vanilla extract',
      '1/2 tsp cinnamon',
      '2 tbsp butter',
      'Maple syrup and fresh fruit for serving',
    ],
    instructions: [
      'In a shallow dish, whisk together eggs, milk, vanilla extract, and cinnamon.',
      'Melt butter in a large skillet over medium heat.',
      'Dip each slice of bread into the egg mixture, allowing it to soak for about 20 seconds per side.',
      'Place the soaked bread onto the hot skillet and cook for 2-3 minutes per side, until golden brown.',
      'Serve immediately with maple syrup and fresh fruit.',
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '15g',
      carbohydrates: '50g',
      fat: '20g',
      fiber: '3g',
      sugar: '15g',
      sodium: '380mg',
    },
  },
  {
    id: 5,
    slug: 'hearty-breakfast-burrito',
    title: 'Hearty Breakfast Burrito',
    category: 'Breakfast',
    cuisine: 'Mexican',
    diet: 'veg',
    image: '/images/recipes/hearty-breakfast-burrito.jpg',
    imageHint: 'breakfast burrito',
    description: 'A filling and customizable breakfast burrito to keep you energized all morning.',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '2 people',
    ingredients: [
      '2 large flour tortillas',
      '4 large eggs, scrambled',
      '1/2 cup cooked black beans, warmed',
      '1/2 cup shredded cheddar cheese',
      '1/4 cup salsa',
      'Optional: cooked sausage or bacon, avocado',
    ],
    instructions: [
      'Warm the tortillas in a dry skillet or microwave until pliable.',
      'Lay a tortilla flat and layer half of the scrambled eggs, black beans, and cheese down the center.',
      'Top with salsa and any other optional fillings.',
      'Fold in the sides of the tortilla, then tightly roll it up from the bottom.',
      'You can either serve immediately or place the burrito seam-side down on a hot skillet to toast for a minute per side.',
      'Repeat with the second tortilla.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '30g',
      carbohydrates: '50g',
      fat: '25g',
      fiber: '8g',
      sugar: '5g',
      sodium: '950mg',
    },
  },
  // Lunch
  {
    id: 6,
    slug: 'vibrant-quinoa-salad',
    title: 'Vibrant Quinoa Salad',
    category: 'Lunch',
    cuisine: 'Mediterranean',
    diet: 'veg',
    image: '/images/recipes/vibrant-quinoa-salad.jpg',
    imageHint: 'quinoa salad',
    description: 'A colorful and nutrient-packed vegetarian quinoa salad with a zesty lemon vinaigrette. This is a vegetarian recipe.',
    prepTime: '15 mins',
    cookTime: '20 mins',
    servings: '4 people',
    ingredients: [
      '1 cup quinoa, rinsed',
      '2 cups water or vegetable broth',
      '1 can (15-ounce) chickpeas, rinsed and drained',
      '1 cup chopped cucumber',
      '1 cup halved cherry tomatoes',
      '1/2 cup chopped red onion',
      '1/4 cup chopped fresh parsley',
      'For the Vinaigrette:',
      '1/4 cup olive oil',
      '1/4 cup lemon juice',
      '1 tsp Dijon mustard',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Cook quinoa according to package directions using water or broth. Fluff with a fork and let cool.',
      'In a large bowl, combine the cooled quinoa, chickpeas, cucumber, cherry tomatoes, red onion, and parsley.',
      'In a small bowl, whisk together the olive oil, lemon juice, Dijon mustard, salt, and pepper.',
      'Pour the vinaigrette over the salad and toss to combine.',
      'Serve immediately or chill for later. It\'s even better the next day!',
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '15g',
      carbohydrates: '60g',
      fat: '18g',
      fiber: '15g',
      sugar: '8g',
      sodium: '400mg',
    },
  },
  {
    id: 7,
    slug: 'caprese-sandwich',
    title: 'Gourmet Caprese Sandwich',
    category: 'Lunch',
    cuisine: 'Italian',
    diet: 'veg',
    image: '/images/recipes/caprese-sandwich.jpg',
    imageHint: 'caprese sandwich',
    description: 'A simple yet elegant sandwich with fresh mozzarella, ripe tomatoes, and basil. This is a vegetarian recipe.',
    prepTime: '10 mins',
    cookTime: '5 mins',
    servings: '1 person',
    ingredients: [
        '2 slices ciabatta or focaccia bread',
        '1 tbsp pesto',
        '1 large ripe tomato, sliced',
        '4 oz fresh mozzarella, sliced',
        'Handful of fresh basil leaves',
        '1 tbsp balsamic glaze',
        '1 tsp olive oil'
    ],
    instructions: [
        'Slice the bread and lightly toast or grill it.',
        'Spread pesto on the inside of both slices of bread.',
        'Layer the tomato slices, mozzarella slices, and fresh basil leaves on the bottom slice.',
        'Drizzle with olive oil and balsamic glaze.',
        'Place the top slice of bread on, press gently, and serve immediately.'
    ],
    nutrition: {
      calories: '500 kcal',
      protein: '20g',
      carbohydrates: '45g',
      fat: '28g',
      fiber: '5g',
      sugar: '10g',
      sodium: '800mg',
    },
  },
  {
    id: 8,
    slug: 'chicken-caesar-wrap',
    title: 'Quick Chicken Caesar Wrap',
    category: 'Lunch',
    cuisine: 'American',
    diet: 'non-veg',
    image: '/images/recipes/chicken-caesar-wrap.jpg',
    imageHint: 'chicken wrap',
    description: 'A classic salad turned into a convenient and delicious wrap for an easy lunch.',
    prepTime: '15 mins',
    cookTime: '0 mins',
    servings: '2 people',
    ingredients: [
        '2 large flour tortillas',
        '2 cups chopped romaine lettuce',
        '1 cup cooked, shredded chicken',
        '1/4 cup Caesar dressing',
        '2 tbsp grated Parmesan cheese',
        '1/4 cup croutons'
    ],
    instructions: [
        'In a medium bowl, toss the romaine lettuce, shredded chicken, Caesar dressing, and Parmesan cheese.',
        'Warm the tortillas slightly to make them more pliable.',
        'Spoon half of the salad mixture onto the center of each tortilla.',
        'Sprinkle croutons over the salad.',
        'Fold in the sides and roll up the wraps tightly.',
        'Slice in half and serve.'
    ],
    nutrition: {
      calories: '480 kcal',
      protein: '25g',
      carbohydrates: '40g',
      fat: '25g',
      fiber: '4g',
      sugar: '4g',
      sodium: '1100mg',
    },
  },
  {
    id: 9,
    slug: 'creamy-lentil-soup',
    title: 'Creamy Red Lentil Soup',
    category: 'Lunch',
    cuisine: 'Middle Eastern',
    diet: 'veg',
    image: '/images/recipes/creamy-lentil-soup.jpg',
    imageHint: 'lentil soup',
    description: 'A comforting and hearty soup that is surprisingly easy to make and full of flavor. This is a vegetarian recipe.',
    prepTime: '10 mins',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '1 tbsp olive oil',
      '1 onion, chopped',
      '2 carrots, chopped',
      '2 cloves garlic, minced',
      '1 cup red lentils, rinsed',
      '4 cups vegetable broth',
      '1 tsp cumin',
      '1/2 tsp turmeric',
      'Juice of 1/2 lemon',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Heat olive oil in a large pot or Dutch oven over medium heat. Add onion and carrots and cook until softened, about 5 minutes.',
      'Add garlic and cook for another minute until fragrant.',
      'Stir in the red lentils, vegetable broth, cumin, and turmeric.',
      'Bring to a boil, then reduce heat and simmer for 20-25 minutes, or until lentils are tender.',
      'For a creamy texture, use an immersion blender to partially or fully blend the soup.',
      'Stir in the lemon juice and season with salt and pepper.',
      'Serve hot, garnished with fresh parsley if desired.'
    ],
    nutrition: {
      calories: '300 kcal',
      protein: '18g',
      carbohydrates: '50g',
      fat: '4g',
      fiber: '20g',
      sugar: '7g',
      sodium: '900mg',
    },
  },
  {
    id: 10,
    slug: 'spicy-tuna-stuffed-avocado',
    title: 'Spicy Tuna Stuffed Avocado',
    category: 'Lunch',
    cuisine: 'American',
    diet: 'non-veg',
    image: '/images/recipes/spicy-tuna-stuffed-avocado.jpg',
    imageHint: 'stuffed avocado',
    description: 'A low-carb, high-protein lunch that is packed with flavor and healthy fats.',
    prepTime: '10 mins',
    cookTime: '0 mins',
    servings: '1 person',
    ingredients: [
      '1 ripe avocado',
      '1 can (5-ounce) tuna, drained',
      '2 tbsp mayonnaise or Greek yogurt',
      '1 tsp sriracha, or to taste',
      '1 tbsp chopped green onion',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Slice the avocado in half and remove the pit.',
      'In a small bowl, mix together the drained tuna, mayonnaise, sriracha, and green onion.',
      'Season the tuna mixture with salt and pepper.',
      'Spoon the tuna salad into the avocado halves.',
      'Garnish with extra green onion and serve immediately.'
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '30g',
      carbohydrates: '15g',
      fat: '32g',
      fiber: '12g',
      sugar: '3g',
      sodium: '500mg',
    },
  },
   {
    id: 18,
    slug: 'greek-salad-with-grilled-chicken',
    title: 'Greek Salad with Grilled Chicken',
    category: 'Lunch',
    cuisine: 'Greek',
    diet: 'non-veg',
    image: '/images/recipes/greek-salad-with-grilled-chicken.jpg',
    imageHint: 'greek salad',
    description: 'A fresh and vibrant Greek salad topped with tender grilled chicken, perfect for a light and healthy lunch.',
    prepTime: '20 mins',
    cookTime: '15 mins',
    servings: '2 people',
    ingredients: [
      '1 lb chicken breast, boneless and skinless',
      '1 tbsp olive oil',
      '1 tsp dried oregano',
      'Salt and pepper to taste',
      '1 head of romaine lettuce, chopped',
      '1 cucumber, diced',
      '1 cup cherry tomatoes, halved',
      '1/2 red onion, thinly sliced',
      '1/2 cup Kalamata olives',
      '4 oz feta cheese, crumbled',
      'For the Dressing:',
      '1/4 cup extra virgin olive oil',
      '2 tbsp red wine vinegar',
      '1 tsp Dijon mustard',
      '1/2 tsp dried oregano',
    ],
    instructions: [
      'Season chicken breasts with olive oil, oregano, salt, and pepper.',
      'Grill or pan-sear the chicken until cooked through, about 6-8 minutes per side. Let it rest, then slice.',
      'In a large bowl, combine lettuce, cucumber, tomatoes, red onion, and olives.',
      'In a small jar, shake together all dressing ingredients until well combined.',
      'Add the sliced chicken and feta cheese to the salad bowl.',
      'Drizzle with dressing, toss gently, and serve immediately.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '45g',
      carbohydrates: '15g',
      fat: '35g',
      fiber: '6g',
      sugar: '8g',
      sodium: '850mg',
    }
  },
  {
    id: 19,
    slug: 'thai-chicken-satay-skewers',
    title: 'Thai Chicken Satay with Peanut Sauce',
    category: 'Lunch',
    cuisine: 'Thai',
    diet: 'non-veg',
    image: '/images/recipes/thai-chicken-satay-skewers.jpg',
    imageHint: 'chicken satay',
    description: 'Deliciously grilled chicken satay skewers served with a creamy peanut dipping sauce.',
    prepTime: '25 mins (plus marination)',
    cookTime: '10 mins',
    servings: '4 people',
    ingredients: [
      '1.5 lbs chicken breast or thighs, cut into strips',
      'Wooden skewers, soaked in water',
      '1/2 cup shredded carrots',
      '1/2 cup sliced cucumber',
      'Fresh cilantro sprigs for garnish',
      'For the Marinade:',
      '1/2 cup coconut milk',
      '2 tbsp soy sauce',
      '1 tbsp honey or brown sugar',
      '1 tsp turmeric',
      '1 tsp ground coriander',
      '2 cloves garlic, minced',
      'For the Peanut Sauce:',
      '1/2 cup creamy peanut butter',
      '1/4 cup warm water',
      '2 tbsp soy sauce',
      '1 tbsp lime juice',
      '1 tsp sriracha (optional)',
    ],
    instructions: [
      'In a bowl, mix all marinade ingredients. Add chicken strips and marinate for at least 30 minutes.',
      'While chicken marinates, whisk together all peanut sauce ingredients until smooth. Add more water if needed to reach desired consistency.',
      'Thread chicken onto the soaked skewers.',
      'Grill or pan-fry over medium-high heat for 3-4 minutes per side, until cooked through and slightly charred.',
      'Serve the hot skewers immediately with the peanut sauce for dipping, and a side of carrots, cucumber, and cilantro.',
    ],
    nutrition: {
      calories: '650 kcal',
      protein: '40g',
      carbohydrates: '50g',
      fat: '35g',
      fiber: '8g',
      sugar: '20g',
      sodium: '1400mg',
    }
  },
  // Dinner
  {
    id: 11,
    slug: 'creamy-tomato-pasta',
    title: 'Ultimate Creamy Tomato Pasta',
    category: 'Dinner',
    cuisine: 'Italian',
    diet: 'veg',
    image: '/images/recipes/creamy-tomato-pasta.jpg',
    imageHint: 'creamy pasta',
    description: "A rich and decadent creamy tomato pasta that comes together in under 30 minutes. Perfect for a busy weeknight. This is a vegetarian recipe.",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: "4 people",
    ingredients: [
      "1 lb (450g) rigatoni",
      "2 tbsp olive oil",
      "1 medium yellow onion, chopped",
      "4 cloves garlic, minced",
      "1 (28-ounce) can crushed tomatoes",
      "1/2 cup heavy cream",
      "1/2 cup grated Parmesan cheese",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
      "1/4 cup fresh basil, chopped",
    ],
    instructions: [
      "Cook pasta according to package directions. Reserve 1 cup pasta water.",
      "Heat olive oil in a large skillet. Add onion and cook until soft.",
      "Add garlic and cook for 1 minute. Add crushed tomatoes and oregano. Simmer for 10 minutes.",
      "Reduce heat. Stir in heavy cream and Parmesan cheese until smooth.",
      "Add cooked pasta to the sauce, adding pasta water if too thick.",
      "Stir in fresh basil and serve immediately.",
    ],
    nutrition: {
      calories: "650 kcal",
      protein: "25g",
      carbohydrates: "80g",
      fat: "28g",
      fiber: '7g',
      sugar: '12g',
      sodium: '1200mg',
    },
  },
  {
    id: 12,
    slug: 'lemon-herb-roast-chicken',
    title: 'Lemon Herb Roast Chicken',
    category: 'Dinner',
    cuisine: 'French',
    diet: 'non-veg',
    image: '/images/recipes/lemon-herb-roast-chicken.jpg',
    imageHint: 'roast chicken',
    description: 'A juicy, flavorful roast chicken that is impressive enough for guests but easy enough for a weeknight.',
    prepTime: '15 mins',
    cookTime: '1 hr 15 mins',
    servings: '4 people',
    ingredients: [
      '1 (3-4 lb) whole chicken',
      '1 lemon, halved',
      '1 head of garlic, cut in half crosswise',
      'Few sprigs of fresh rosemary and thyme',
      '2 tbsp olive oil',
      'Salt and freshly ground black pepper',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C).',
      'Pat the chicken dry with paper towels. Rub it all over with olive oil and season generously with salt and pepper.',
      'Stuff the cavity of the chicken with the lemon halves, garlic, and fresh herbs.',
      'Place the chicken in a roasting pan or large oven-safe skillet.',
      'Roast for 1 hour and 15 minutes, or until the juices run clear when a thigh is pierced.',
      'Let the chicken rest for 10-15 minutes before carving. Serve with pan juices.',
    ],
    nutrition: {
      calories: '700 kcal',
      protein: '70g',
      carbohydrates: '5g',
      fat: '45g',
      fiber: '1g',
      sugar: '2g',
      sodium: '600mg',
    },
  },
  {
    id: 13,
    slug: 'black-bean-burgers',
    title: 'Best-Ever Black Bean Burgers',
    category: 'Dinner',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/black-bean-burgers.jpg',
    imageHint: 'bean burger',
    description: 'Hearty and flavorful homemade vegetarian black bean burgers that even meat-eaters will love. This is a vegetarian recipe.',
    prepTime: '20 mins',
    cookTime: '10 mins',
    servings: '4 burgers',
    ingredients: [
      '1 can (15-ounce) black beans, rinsed and patted dry',
      '1/2 green bell pepper, chopped',
      '1/2 onion, chopped',
      '2 cloves garlic',
      '1 egg',
      '1 tbsp chili powder',
      '1 tbsp cumin',
      '1/2 cup bread crumbs',
      '4 hamburger buns and your favorite toppings',
    ],
    instructions: [
      'In a food processor, combine bell pepper, onion, and garlic. Pulse until finely chopped.',
      'Add black beans, egg, chili powder, and cumin. Pulse until combined but still chunky.',
      'Transfer mixture to a bowl and stir in bread crumbs. Let sit for 5 minutes.',
      'Divide mixture into 4 equal portions and shape into patties.',
      'Heat a lightly oiled skillet over medium heat. Cook burgers for 5-7 minutes per side, until browned and firm.',
      'Serve on buns with your favorite toppings like lettuce, tomato, and avocado.',
    ],
    nutrition: {
      calories: '400 kcal',
      protein: '20g',
      carbohydrates: '60g',
      fat: '10g',
      fiber: '15g',
      sugar: '9g',
      sodium: '750mg',
    },
  },
  {
    id: 14,
    slug: 'sheet-pan-salmon-and-veggies',
    title: 'Sheet Pan Salmon & Veggies',
    category: 'Dinner',
    cuisine: 'Mediterranean',
    diet: 'non-veg',
    image: '/images/recipes/sheet-pan-salmon-and-veggies.jpg',
    imageHint: 'salmon veggies',
    description: 'A healthy, delicious, and incredibly easy one-pan dinner for minimal cleanup.',
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: '2 people',
    ingredients: [
      '2 (6-ounce) salmon fillets',
      '1 lb asparagus, trimmed',
      '1 pint cherry tomatoes',
      '2 tbsp olive oil',
      '1 tsp dried herbs (like oregano or Italian seasoning)',
      'Salt and pepper to taste',
      'Lemon wedges for serving',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'On a large baking sheet, toss the asparagus and cherry tomatoes with 1 tbsp of olive oil, dried herbs, salt, and pepper.',
      'Roast the vegetables for 10 minutes.',
      'While vegetables roast, pat the salmon fillets dry and rub with the remaining 1 tbsp of olive oil. Season with salt and pepper.',
      'Remove the baking sheet from the oven, push the vegetables to the sides, and place the salmon in the center.',
      'Return to the oven and bake for another 10-12 minutes, or until the salmon is cooked through.',
      'Serve immediately with fresh lemon wedges.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '40g',
      carbohydrates: '20g',
      fat: '35g',
      fiber: '8g',
      sugar: '10g',
      sodium: '450mg',
    },
  },
  {
    id: 15,
    slug: 'easy-beef-stir-fry',
    title: 'Easy Beef Stir-Fry',
    category: 'Dinner',
    cuisine: 'Asian',
    diet: 'non-veg',
    image: '/images/recipes/easy-beef-stir-fry.jpg',
    imageHint: 'beef stirfry',
    description: 'A quick and easy beef stir-fry that\'s better than takeout and ready in 30 minutes.',
    prepTime: '15 mins',
    cookTime: '15 mins',
    servings: '4 people',
    ingredients: [
      '1 lb flank steak, thinly sliced against the grain',
      '1 tbsp cornstarch',
      '2 tbsp soy sauce',
      '1 tbsp sesame oil',
      '1 head of broccoli, cut into florets',
      '1 red bell pepper, sliced',
      '4 cloves garlic, minced',
      '1 tbsp grated ginger',
      'Cooked rice for serving',
    ],
    instructions: [
      'In a bowl, toss the sliced beef with cornstarch.',
      'In a separate small bowl, whisk together soy sauce and sesame oil for the sauce.',
      'Heat 1 tbsp of vegetable oil in a large skillet or wok over high heat. Add beef and cook until browned. Remove from skillet.',
      'Add a little more oil to the skillet. Add broccoli and bell pepper and stir-fry for 3-4 minutes.',
      'Add garlic and ginger and cook for 1 more minute.',
      'Return the beef to the skillet. Pour the sauce over everything and toss to combine until the sauce has thickened.',
      'Serve immediately over cooked rice.',
    ],
    nutrition: {
      calories: '500 kcal',
      protein: '35g',
      carbohydrates: '40g',
      fat: '22g',
      fiber: '5g',
      sugar: '15g',
      sodium: '1500mg',
    },
  },
  {
    id: 16,
    slug: 'chicken-tikka-masala',
    title: 'Chicken Tikka Masala',
    category: 'Dinner',
    cuisine: 'Indian',
    diet: 'non-veg',
    image: '/images/recipes/chicken-tikka-masala.jpg',
    imageHint: 'chicken curry',
    description: 'A rich and creamy curry that is a staple in Indian cuisine. Perfect with naan or rice.',
    prepTime: '20 mins (plus marination)',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '1.5 lbs boneless, skinless chicken breasts, cut into 1-inch cubes',
      '1 cup plain yogurt',
      '1 tbsp lemon juice',
      '2 tsp ground cumin',
      '2 tsp paprika',
      '1 tsp turmeric',
      '1 tsp garam masala',
      '1 tbsp minced ginger',
      '2 cloves garlic, minced',
      '1 tbsp vegetable oil',
      '1 large onion, chopped',
      '1 (15-ounce) can tomato sauce',
      '1 cup heavy cream',
      'Fresh cilantro for garnish',
    ],
    instructions: [
      'In a bowl, combine yogurt, lemon juice, cumin, paprika, turmeric, garam masala, ginger, and garlic. Add chicken and toss to coat. Marinate for at least 1 hour.',
      'Heat oil in a large skillet over medium-high heat. Add chicken and cook until browned on all sides. Remove chicken from skillet.',
      'Add onion to the skillet and cook until soft. Stir in tomato sauce and cook for 5 minutes.',
      'Stir in heavy cream and bring to a simmer. Return chicken to the skillet.',
      'Simmer for 10-15 minutes until chicken is cooked through and sauce has thickened.',
      'Garnish with cilantro and serve with rice or naan bread.',
    ],
    nutrition: {
      calories: '600 kcal',
      protein: '50g',
      carbohydrates: '20g',
      fat: '38g',
      fiber: '4g',
      sugar: '10g',
      sodium: '1300mg',
    },
  },
  {
    id: 17,
    slug: 'classic-beef-tacos',
    title: 'Classic Beef Tacos',
    category: 'Dinner',
    cuisine: 'Mexican',
    diet: 'non-veg',
    image: '/images/recipes/classic-beef-tacos.jpg',
    imageHint: 'beef tacos',
    description: 'A family-favorite taco recipe that is quick, easy, and endlessly customizable.',
    prepTime: '10 mins',
    cookTime: '15 mins',
    servings: '4 people',
    ingredients: [
      '1 lb ground beef',
      '1 packet taco seasoning',
      '3/4 cup water',
      '12 hard taco shells or small flour tortillas',
      'Toppings: shredded lettuce, diced tomatoes, shredded cheddar cheese, salsa, sour cream'
    ],
    instructions: [
      'In a large skillet, cook ground beef over medium-high heat until no longer pink. Drain excess fat.',
      'Stir in taco seasoning and water. Bring to a simmer and cook for 5-7 minutes, until the sauce has thickened.',
      'Warm taco shells or tortillas according to package directions.',
      'Spoon the beef mixture into the shells.',
      'Set up a topping bar with lettuce, tomatoes, cheese, salsa, and sour cream, and let everyone build their own tacos.',
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '25g',
      carbohydrates: '30g',
      fat: '25g',
      fiber: '6g',
      sugar: '5g',
      sodium: '1000mg',
    },
  },
  {
    id: 20,
    slug: 'thai-green-curry-chicken',
    title: 'Authentic Thai Green Curry',
    category: 'Dinner',
    cuisine: 'Thai',
    diet: 'non-veg',
    image: '/images/recipes/thai-green-curry-chicken.jpg',
    imageHint: 'thai curry',
    description: 'A fragrant and spicy Thai green curry with tender chicken and vegetables, all simmered in coconut milk.',
    prepTime: '15 mins',
    cookTime: '25 mins',
    servings: '4 people',
    ingredients: [
      '1.5 lbs chicken breast, cubed',
      '1 tbsp coconut oil',
      '1/4 cup green curry paste',
      '1 can (13.5-ounce) full-fat coconut milk',
      '1 cup chicken broth',
      '1 red bell pepper, sliced',
      '1 cup snow peas',
      '1 tbsp fish sauce',
      '1 tsp sugar',
      'Fresh basil leaves for garnish',
      'Jasmine rice for serving',
    ],
    instructions: [
      'Heat coconut oil in a large pot or skillet over medium-high heat.',
      'Add the green curry paste and cook for 1 minute until fragrant.',
      'Add the cubed chicken and cook until lightly browned.',
      'Stir in the coconut milk and chicken broth. Bring to a simmer.',
      'Reduce heat and cook for 15 minutes, stirring occasionally.',
      'Add the bell pepper and snow peas and cook for another 5-7 minutes, until vegetables are tender-crisp.',
      'Stir in the fish sauce and sugar.',
      'Serve hot over jasmine rice, garnished with fresh basil.',
    ],
    nutrition: {
      calories: '580 kcal',
      protein: '45g',
      carbohydrates: '25g',
      fat: '35g',
      fiber: '6g',
      sugar: '10g',
      sodium: '1600mg',
    }
  },
  {
    id: 21,
    slug: 'spanish-garlic-shrimp',
    title: 'Spanish Garlic Shrimp (Gambas al Ajillo)',
    category: 'Dinner',
    cuisine: 'Spanish',
    diet: 'non-veg',
    image: '/images/recipes/spanish-garlic-shrimp.jpg',
    imageHint: 'garlic shrimp',
    description: 'A classic Spanish tapa of shrimp sizzled in olive oil with lots of garlic and a touch of chili.',
    prepTime: '10 mins',
    cookTime: '10 mins',
    servings: '4 people (as a tapa)',
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '1/2 cup extra virgin olive oil',
      '10-12 cloves garlic, thinly sliced',
      '1/2 tsp red pepper flakes',
      '2 tbsp dry sherry or white wine',
      '2 tbsp chopped fresh parsley',
      'Crusty bread for serving',
    ],
    instructions: [
      'Heat olive oil in a large skillet or cazuela over medium heat.',
      'Add the sliced garlic and red pepper flakes. Cook until the garlic is golden and fragrant, but not burnt (about 1-2 minutes).',
      'Turn the heat up to high, add the shrimp to the skillet in a single layer.',
      'Cook the shrimp for 1-2 minutes per side, until they turn pink and opaque.',
      'Pour in the sherry, and let it bubble for 30 seconds, scraping up any browned bits.',
      'Remove from heat, stir in the parsley, and season with salt.',
      'Serve immediately in the skillet with crusty bread for dipping in the garlic oil.',
    ],
    nutrition: {
      calories: '350 kcal',
      protein: '22g',
      carbohydrates: '5g',
      fat: '25g',
      fiber: '1g',
      sugar: '1g',
      sodium: '700mg',
    }
  },
  {
    id: 22,
    slug: 'classic-beef-lasagna',
    title: 'Classic Beef Lasagna',
    category: 'Dinner',
    cuisine: 'Italian',
    diet: 'non-veg',
    image: '/images/recipes/classic-beef-lasagna.jpg',
    imageHint: 'lasagna dinner',
    description: 'Layers of rich meat sauce, creamy béchamel, and tender pasta, baked to golden perfection.',
    prepTime: '30 mins',
    cookTime: '1 hr',
    servings: '6-8 people',
    ingredients: [
      '1 lb ground beef',
      '1 onion, chopped',
      '2 cloves garlic, minced',
      '1 (28-ounce) can crushed tomatoes',
      '2 (6-ounce) cans tomato paste',
      '1/2 cup water',
      '2 tsp sugar',
      '1.5 tsp dried basil',
      '1/2 tsp fennel seeds',
      '1 tsp salt',
      '1/4 tsp black pepper',
      '12 lasagna noodles, cooked',
      '16 oz ricotta cheese',
      '1 egg',
      '1/2 cup grated Parmesan cheese',
      '1 lb mozzarella cheese, sliced',
    ],
    instructions: [
      'In a Dutch oven, cook beef, onion, and garlic over medium heat until browned. Drain fat.',
      'Stir in crushed tomatoes, tomato paste, water, sugar, basil, fennel, salt, and pepper. Bring to a boil, reduce heat, and simmer for 1 hour, stirring occasionally.',
      'Preheat oven to 375°F (190°C).',
      'In a bowl, mix ricotta cheese, egg, and half of the Parmesan cheese.',
      'To assemble, spread 1.5 cups of meat sauce in the bottom of a 9x13 inch baking dish.',
      'Arrange noodles over meat sauce. Spread with half of the ricotta mixture. Top with a third of the mozzarella slices.',
      'Repeat layers. Top with remaining meat sauce and mozzarella and Parmesan cheese.',
      'Bake for 25-30 minutes or until bubbly. Let stand for 10 minutes before serving.',
    ],
    nutrition: {
      calories: '750 kcal',
      protein: '45g',
      carbohydrates: '60g',
      fat: '38g',
      fiber: '8g',
      sugar: '15g',
      sodium: '1800mg',
    }
  },
  {
    id: 23,
    slug: 'classic-caesar-salad',
    title: 'Classic Caesar Salad with Grilled Chicken',
    category: 'Lunch',
    cuisine: 'American',
    diet: 'non-veg',
    image: '/images/recipes/classic-caesar-salad.jpg',
    imageHint: 'caesar salad',
    description: 'The timeless classic, elevated with tender grilled chicken. Crisp romaine, creamy Caesar dressing, crunchy croutons, and sharp Parmesan cheese.',
    prepTime: '15 mins',
    cookTime: '10 mins',
    servings: '2 people',
    ingredients: [
        '1 large chicken breast',
        '1 head romaine lettuce, chopped',
        '1 cup croutons',
        '1/2 cup grated Parmesan cheese',
        'For the dressing:',
        '1/2 cup mayonnaise',
        '2 tbsp lemon juice',
        '1 tsp Dijon mustard',
        '1 clove garlic, minced',
        'Salt and pepper to taste'
    ],
    instructions: [
        'Season chicken breast with salt and pepper. Grill or pan-sear until cooked through. Let rest, then slice.',
        'In a small bowl, whisk together all dressing ingredients.',
        'In a large salad bowl, combine the chopped romaine, sliced chicken, croutons, and Parmesan cheese.',
        'Drizzle with Caesar dressing and toss gently to coat.',
        'Serve immediately.'
    ],
    nutrition: { calories: '550 kcal', protein: '40g', carbohydrates: '15g', fat: '35g', fiber: '4g', sugar: '5g', sodium: '900mg' }
  },
  {
    id: 24,
    slug: 'zesty-italian-pasta-salad',
    title: 'Zesty Italian Pasta Salad',
    category: 'Lunch',
    cuisine: 'Italian',
    diet: 'non-veg',
    image: '/images/recipes/zesty-italian-pasta-salad.jpg',
    imageHint: 'pasta salad',
    description: 'A colorful and tangy pasta salad loaded with fresh veggies, salami, and mozzarella, all tossed in a zesty Italian dressing.',
    prepTime: '20 mins',
    cookTime: '10 mins',
    servings: '6-8 people',
    ingredients: [
        '1 lb rotini pasta, cooked and cooled',
        '1 cup cherry tomatoes, halved',
        '1 cup cucumber, diced',
        '1/2 red onion, thinly sliced',
        '1/2 cup black olives, sliced',
        '4 oz salami, diced',
        '4 oz fresh mozzarella pearls',
        'For the dressing:',
        '1/2 cup olive oil',
        '1/4 cup red wine vinegar',
        '1 tbsp Dijon mustard',
        '1 tsp dried oregano',
        'Salt and pepper to taste'
    ],
    instructions: [
        'Cook pasta according to package directions. Drain, rinse with cold water, and set aside.',
        'In a large bowl, combine the cooled pasta, tomatoes, cucumber, red onion, olives, salami, and mozzarella.',
        'In a small bowl or jar, whisk or shake together all the dressing ingredients.',
        'Pour the dressing over the pasta salad and toss everything to combine.',
        'Cover and refrigerate for at least 30 minutes to allow the flavors to meld.',
        'Serve chilled or at room temperature.'
    ],
    nutrition: { calories: '480 kcal', protein: '15g', carbohydrates: '55g', fat: '22g', fiber: '6g', sugar: '8g', sodium: '1200mg' }
  },
  {
    id: 25,
    slug: 'creamy-mushroom-risotto',
    title: 'Creamy Mushroom Risotto',
    category: 'Dinner',
    cuisine: 'Italian',
    diet: 'veg',
    image: '/images/recipes/creamy-mushroom-risotto.jpg',
    imageHint: 'mushroom risotto',
    description: 'A creamy and savory vegetarian risotto made with Arborio rice, fresh mushrooms, and Parmesan cheese. A true comfort food classic. This is a vegetarian recipe.',
    prepTime: '10 mins',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '1 tbsp olive oil',
      '1 lb cremini mushrooms, sliced',
      '1 shallot, finely chopped',
      '2 cloves garlic, minced',
      '1 1/2 cups Arborio rice',
      '1/2 cup dry white wine',
      '6 cups vegetable broth, warmed',
      '1/2 cup grated Parmesan cheese',
      '2 tbsp butter',
      'Fresh parsley, chopped, for garnish',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a large skillet, heat olive oil over medium-high heat. Add mushrooms and cook until browned. Set aside.',
      'In the same skillet, add a bit more oil if needed. Add shallot and cook until translucent.',
      'Add garlic and Arborio rice, stirring for 1 minute to toast the rice.',
      'Pour in the white wine and cook until it is fully absorbed, stirring constantly.',
      'Add one ladle of warm vegetable broth to the rice, stirring until it is absorbed. Continue adding broth one ladle at a time, allowing each addition to be absorbed before adding the next. This process should take about 15-20 minutes.',
      'When the rice is tender and creamy, stir in the cooked mushrooms, Parmesan cheese, and butter.',
      'Season with salt and pepper. Garnish with fresh parsley before serving.',
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '15g',
      carbohydrates: '70g',
      fat: '20g',
      fiber: '5g',
      sugar: '6g',
      sodium: '1100mg',
    },
  },
  {
    id: 26,
    slug: 'spinach-feta-stuffed-peppers',
    title: 'Spinach and Feta Stuffed Peppers',
    category: 'Dinner',
    cuisine: 'Mediterranean',
    diet: 'veg',
    image: '/images/recipes/spinach-feta-stuffed-peppers.jpg',
    imageHint: 'stuffed peppers',
    description: 'Colorful bell peppers filled with a delicious vegetarian mixture of spinach, feta cheese, quinoa, and herbs. This is a vegetarian recipe.',
    prepTime: '15 mins',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '4 large bell peppers, any color, halved and seeded',
      '1 tbsp olive oil',
      '1 onion, chopped',
      '3 cloves garlic, minced',
      '5 oz fresh spinach',
      '1 cup cooked quinoa',
      '1 cup crumbled feta cheese',
      '1/4 cup chopped fresh dill',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Place pepper halves cut-side up in a baking dish. Drizzle with a little olive oil and bake for 15 minutes to soften.',
      'Meanwhile, heat 1 tbsp olive oil in a skillet over medium heat. Add onion and cook until soft.',
      'Add garlic and cook for another minute. Add spinach and cook until wilted. Drain any excess liquid.',
      'In a bowl, combine the spinach mixture, cooked quinoa, feta cheese, and dill. Season with salt and pepper.',
      'Spoon the filling into the partially baked pepper halves.',
      'Bake for an additional 15-20 minutes, or until the peppers are tender and the filling is heated through.',
    ],
    nutrition: {
      calories: '350 kcal',
      protein: '15g',
      carbohydrates: '35g',
      fat: '18g',
      fiber: '8g',
      sugar: '12g',
      sodium: '700mg',
    },
  },
  {
    id: 27,
    slug: 'lentil-shepherds-pie',
    title: 'Hearty Lentil Shepherd\'s Pie',
    category: 'Dinner',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/lentil-shepherds-pie.jpg',
    imageHint: 'shepherds pie',
    description: 'A comforting and savory vegetarian shepherd\'s pie with a rich lentil filling and a creamy mashed potato topping. This is a vegetarian recipe.',
    prepTime: '25 mins',
    cookTime: '40 mins',
    servings: '6 people',
    ingredients: [
      'For the filling:',
      '2 tbsp olive oil',
      '1 onion, chopped',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '8 oz cremini mushrooms, chopped',
      '1 cup brown or green lentils, rinsed',
      '4 cups vegetable broth',
      '2 tbsp tomato paste',
      '1 tsp dried thyme',
      'For the topping:',
      '2 lbs potatoes, peeled and cubed',
      '1/2 cup milk or non-dairy milk',
      '4 tbsp butter or vegan butter',
      'Salt and pepper to taste',
    ],
    instructions: [
      'For the topping, boil potatoes until tender. Drain and mash with milk, butter, salt, and pepper until creamy.',
      'For the filling, heat olive oil in a large oven-safe skillet or pot over medium heat. Add onion, carrots, and celery, cooking until softened.',
      'Add mushrooms and cook until they release their liquid and start to brown.',
      'Stir in the tomato paste and thyme. Add the rinsed lentils and vegetable broth. Bring to a boil, then reduce heat and simmer for 30-40 minutes, or until lentils are tender and the mixture has thickened.',
      'Preheat oven to 375°F (190°C).',
      'Spread the lentil filling evenly in the skillet or a baking dish.',
      'Top with the mashed potatoes, spreading them evenly. Use a fork to create some texture on top.',
      'Bake for 20-25 minutes, or until the filling is bubbly and the potato topping is golden brown.',
    ],
    nutrition: {
      calories: '480 kcal',
      protein: '20g',
      carbohydrates: '75g',
      fat: '12g',
      fiber: '22g',
      sugar: '15g',
      sodium: '850mg',
    },
  },
  {
    id: 28,
    slug: 'instant-pot-lentil-soup',
    title: 'Instant Pot Lentil Soup',
    category: 'Dinner',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/instant-pot-lentil-soup.jpg',
    imageHint: 'lentil soup instant pot',
    description: 'A quick, hearty, and flavorful lentil soup made incredibly easy in the Instant Pot. A perfect one-pot meal. This is a vegetarian recipe.',
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: '6 people',
    ingredients: [
      '1 tbsp olive oil',
      '1 large onion, chopped',
      '2 carrots, chopped',
      '2 celery stalks, chopped',
      '4 cloves garlic, minced',
      '1 1/2 cups brown or green lentils, rinsed',
      '6 cups vegetable broth',
      '1 (14.5-ounce) can diced tomatoes, undrained',
      '1 tsp dried thyme',
      '1/2 tsp smoked paprika',
      'Salt and pepper to taste',
      '1 tbsp lemon juice'
    ],
    instructions: [
      'Set the Instant Pot to the "Sauté" function. Add olive oil, onion, carrots, and celery. Cook for 5 minutes until softened.',
      'Add garlic and cook for another minute until fragrant.',
      'Press "Cancel". Add rinsed lentils, vegetable broth, diced tomatoes, thyme, and smoked paprika. Stir to combine.',
      'Secure the lid and set the steam release valve to "Sealing". Select "Manual" or "Pressure Cook" and set the timer for 15 minutes at high pressure.',
      'When the time is up, let the pressure release naturally for 10 minutes, then perform a quick release for any remaining pressure.',
      'Carefully open the lid. Stir in the lemon juice and season with salt and pepper to taste.',
      'Serve hot, garnished with fresh parsley if desired.'
    ],
    nutrition: {
        calories: '280 kcal',
        protein: '15g',
        carbohydrates: '45g',
        fat: '4g',
        fiber: '18g',
        sugar: '9g',
        sodium: '750mg'
    }
  },
  {
    id: 29,
    slug: 'instant-pot-pot-roast',
    title: 'Instant Pot Pot Roast',
    category: 'Dinner',
    cuisine: 'American',
    diet: 'non-veg',
    image: '/images/recipes/instant-pot-pot-roast.jpg',
    imageHint: 'pot roast',
    description: 'Fall-apart tender pot roast with potatoes and carrots, cooked to perfection in a fraction of the time using the Instant Pot.',
    prepTime: '15 mins',
    cookTime: '1 hr 30 mins',
    servings: '6 people',
    ingredients: [
        '3 lb beef chuck roast',
        '2 tbsp olive oil',
        '1 large onion, chopped',
        '4 cloves garlic, minced',
        '1 cup beef broth',
        '1/4 cup Worcestershire sauce',
        '1 tbsp tomato paste',
        '1 tsp dried thyme',
        '1.5 lbs baby potatoes, halved',
        '4 large carrots, cut into 1-inch chunks',
        '2 tbsp cornstarch',
        '2 tbsp cold water'
    ],
    instructions: [
        'Season the chuck roast generously with salt and pepper.',
        'Set the Instant Pot to "Sauté" on high. Add olive oil. Once hot, sear the roast for 3-4 minutes per side until well browned. Remove roast and set aside.',
        'Add onion to the pot and cook for 3-4 minutes until softened. Add garlic and cook for 1 more minute.',
        'Pour in beef broth to deglaze the pot, scraping up any browned bits from the bottom.',
        'Stir in Worcestershire sauce, tomato paste, and thyme. Turn off the "Sauté" function.',
        'Return the roast to the pot. Add the potatoes and carrots around the roast.',
        'Secure the lid, set the valve to "Sealing". Cook on high pressure for 60 minutes.',
        'Once done, let the pressure release naturally for 15 minutes, then quick release the remaining pressure.',
        'Remove the roast and vegetables to a platter. Set the Instant Pot back to "Sauté".',
        'In a small bowl, whisk together cornstarch and cold water to make a slurry. Whisk it into the liquid in the pot and simmer until the gravy has thickened.',
        'Slice the roast and serve with the vegetables and gravy.'
    ],
    nutrition: {
        calories: '650 kcal',
        protein: '50g',
        carbohydrates: '30g',
        fat: '35g',
        fiber: '5g',
        sugar: '8g',
        sodium: '800mg'
    }
  },
  {
    id: 30,
    slug: 'instant-pot-chana-masala',
    title: 'Instant Pot Chana Masala',
    category: 'Dinner',
    cuisine: 'Indian',
    diet: 'veg',
    image: '/images/recipes/instant-pot-chana-masala.jpg',
    imageHint: 'chana masala',
    description: 'A flavorful and hearty chickpea curry made incredibly fast and easy in the Instant Pot. A perfect vegetarian weeknight meal. This is a vegetarian recipe.',
    prepTime: '10 mins',
    cookTime: '20 mins',
    servings: '4 people',
    ingredients: [
      '1 tbsp vegetable oil',
      '1 large onion, chopped',
      '1 tbsp minced ginger',
      '3 cloves garlic, minced',
      '1 (14.5-ounce) can diced tomatoes, undrained',
      '2 (15-ounce) cans chickpeas, rinsed and drained',
      '1 tbsp chana masala powder (or 1 tsp cumin, 1 tsp coriander, 1/2 tsp turmeric)',
      '1/2 tsp garam masala',
      '1/4 tsp cayenne pepper (optional)',
      '1 cup water or vegetable broth',
      'Salt to taste',
      'Juice of 1/2 lemon',
      'Fresh cilantro for garnish'
    ],
    instructions: [
      'Set the Instant Pot to "Sauté" mode. Add oil, then add the onion and cook until softened, about 3-4 minutes.',
      'Add ginger and garlic and sauté for another minute until fragrant.',
      'Stir in the diced tomatoes, chana masala powder, garam masala, and cayenne pepper. Cook for 1 minute.',
      'Press "Cancel". Add the chickpeas and water/broth. Season with salt. Stir well.',
      'Secure the lid and set the valve to "Sealing". Select "Pressure Cook" or "Manual" and cook on high pressure for 5 minutes.',
      'Once the cooking is complete, let the pressure release naturally for 10 minutes, then perform a quick release.',
      'Open the lid, stir in the lemon juice, and garnish with fresh cilantro.',
      'Serve hot with rice or naan bread.'
    ],
    nutrition: {
        calories: '350 kcal',
        protein: '14g',
        carbohydrates: '60g',
        fat: '7g',
        fiber: '15g',
        sugar: '10g',
        sodium: '800mg'
    }
  },
  {
    id: 31,
    slug: 'vegan-chickpea-salad-sandwich',
    title: 'Vegan Chickpea Salad Sandwich',
    category: 'Lunch',
    cuisine: 'American',
    diet: 'veg',
    image: '/images/recipes/vegan-chickpea-salad-sandwich.jpg',
    imageHint: 'chickpea sandwich',
    description: 'A delicious and easy vegan alternative to tuna salad, perfect for a quick lunch or meal prep. This recipe is fully vegan.',
    prepTime: '15 mins',
    cookTime: '0 mins',
    servings: '2 sandwiches',
    ingredients: [
      '1 (15-ounce) can chickpeas, rinsed and drained',
      '1/4 cup vegan mayonnaise',
      '1 celery stalk, finely chopped',
      '2 tbsp red onion, finely chopped',
      '1 tbsp Dijon mustard',
      '1 tbsp fresh dill, chopped',
      'Salt and pepper to taste',
      '4 slices of your favorite bread',
      'Lettuce and tomato slices for serving'
    ],
    instructions: [
      'In a medium bowl, mash the chickpeas with a fork or potato masher until flaky.',
      'Add the vegan mayonnaise, celery, red onion, Dijon mustard, and dill to the bowl.',
      'Mix everything together until well combined. Season with salt and pepper to taste.',
      'Toast your bread slices if desired.',
      'Divide the chickpea salad mixture evenly between two slices of bread.',
      'Top with lettuce and tomato, then add the remaining two slices of bread to complete the sandwiches.',
      'Serve immediately.'
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '15g',
      carbohydrates: '65g',
      fat: '15g',
      fiber: '12g',
      sugar: '8g',
      sodium: '800mg',
    }
  },
  {
    id: 32,
    slug: 'creamy-vegan-tomato-soup',
    title: 'Creamy Vegan Tomato Soup',
    category: 'Dinner',
    cuisine: 'Italian',
    diet: 'veg',
    image: '/images/recipes/creamy-vegan-tomato-soup.jpg',
    imageHint: 'tomato soup',
    description: 'A rich and creamy vegan tomato soup, perfect for a comforting meal. Great for meal prep, this is a fully vegan dish.',
    prepTime: '10 mins',
    cookTime: '25 mins',
    servings: '4 people',
    ingredients: [
      '1 tbsp olive oil',
      '1 large yellow onion, chopped',
      '3 cloves garlic, minced',
      '1 (28-ounce) can crushed tomatoes',
      '1 cup vegetable broth',
      '1/2 cup full-fat coconut milk (from a can)',
      '1 tsp dried basil',
      '1 tsp sugar (optional, to balance acidity)',
      'Salt and pepper to taste',
      'Fresh basil for garnish'
    ],
    instructions: [
      'Heat olive oil in a large pot or Dutch oven over medium heat. Add the onion and cook until softened, about 5-7 minutes.',
      'Add the minced garlic and cook for another minute until fragrant.',
      'Pour in the crushed tomatoes and vegetable broth. Add the dried basil and sugar (if using).',
      'Bring the soup to a simmer, then reduce the heat, cover, and let it cook for 15 minutes.',
      'Use an immersion blender to blend the soup until smooth. Alternatively, carefully transfer it to a regular blender and blend in batches.',
      'Return the soup to the pot. Stir in the coconut milk and heat through gently. Do not let it boil.',
      'Season with salt and pepper to taste. Serve hot, garnished with fresh basil.'
    ],
    nutrition: {
      calories: '250 kcal',
      protein: '5g',
      carbohydrates: '25g',
      fat: '15g',
      fiber: '6g',
      sugar: '15g',
      sodium: '650mg',
    }
  },
  {
    id: 33,
    slug: 'meal-prep-burrito-bowls',
    title: 'Chicken Burrito Bowls for Meal Prep',
    category: 'Lunch',
    cuisine: 'Mexican',
    diet: 'non-veg',
    image: '/images/recipes/meal-prep-burrito-bowls.jpg',
    imageHint: 'burrito bowl',
    description: 'A healthy and delicious meal prep solution. Customizable burrito bowls with seasoned chicken, cilantro-lime rice, beans, and fresh toppings.',
    prepTime: '20 mins',
    cookTime: '25 mins',
    servings: '4 bowls',
    ingredients: [
      '1 lb boneless, skinless chicken breast, cut into bite-sized pieces',
      '1 tbsp olive oil',
      '1 packet taco seasoning',
      '1 cup uncooked long-grain white rice',
      '2 cups water',
      '1/4 cup chopped fresh cilantro',
      'Juice of 1 lime',
      '1 (15-ounce) can black beans, rinsed and drained',
      '1 cup corn (frozen or canned)',
      'For serving: salsa, shredded lettuce, avocado, or shredded cheese'
    ],
    instructions: [
      'In a bowl, toss the chicken pieces with olive oil and taco seasoning.',
      'Heat a large skillet over medium-high heat. Add the chicken and cook until browned and cooked through, about 5-7 minutes. Set aside.',
      'Cook rice with water according to package directions. Once cooked, fluff with a fork and stir in the cilantro and lime juice.',
      'To assemble the meal prep bowls, divide the cilantro-lime rice evenly among four containers.',
      'Top the rice with the cooked chicken, black beans, and corn.',
      'Store in the refrigerator for up to 4 days. When ready to eat, reheat and add fresh toppings like salsa, lettuce, and avocado.'
    ],
    nutrition: {
      calories: '550 kcal',
      protein: '40g',
      carbohydrates: '65g',
      fat: '12g',
      fiber: '10g',
      sugar: '5g',
      sodium: '950mg',
    }
  },
  {
    id: 34,
    slug: 'sheet-pan-chicken-meal-prep',
    title: 'Sheet Pan Chicken and Veggies for Meal Prep',
    category: 'Dinner',
    cuisine: 'Mediterranean',
    diet: 'non-veg',
    image: '/images/recipes/sheet-pan-chicken-veggies.jpg',
    imageHint: 'sheet pan chicken',
    description: 'An incredibly easy one-pan dinner that is perfect for a healthy weeknight eating or meal prep for the week. Minimal cleanup required.',
    prepTime: '15 mins',
    cookTime: '30 mins',
    servings: '4 servings',
    ingredients: [
      '1.5 lbs boneless, skinless chicken breasts, cut into 1-inch chunks',
      '1 lb broccoli florets',
      '1 red bell pepper, chopped',
      '1 red onion, cut into wedges',
      '2 tbsp olive oil',
      '1 tbsp lemon juice',
      '1 tsp dried oregano',
      '1 tsp dried basil',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'On a large baking sheet, combine the chicken chunks, broccoli, bell pepper, and red onion.',
      'In a small bowl, whisk together the olive oil, lemon juice, oregano, basil, salt, and pepper.',
      'Pour the olive oil mixture over the chicken and vegetables on the baking sheet and toss until everything is evenly coated.',
      'Spread the mixture in a single layer on the baking sheet.',
      'Bake for 25-30 minutes, or until the chicken is cooked through and the vegetables are tender and slightly browned.',
      'Divide into four containers for meal prep. Serve on its own or with a side of quinoa or rice.'
    ],
    nutrition: {
      calories: '420 kcal',
      protein: '45g',
      carbohydrates: '15g',
      fat: '20g',
      fiber: '6g',
      sugar: '8g',
      sodium: '400mg',
    }
  },
  {
    id: 35,
    slug: 'paneer-butter-masala',
    title: 'Paneer Butter Masala',
    category: 'Dinner',
    cuisine: 'Indian',
    diet: 'veg',
    image: '/images/recipes/paneer-butter-masala.jpg',
    imageHint: 'paneer curry',
    description: 'A classic, creamy, and indulgent Indian curry made with paneer cheese in a rich tomato and butter sauce. This is a vegetarian recipe.',
    prepTime: '15 mins',
    cookTime: '30 mins',
    servings: '4 people',
    ingredients: [
      '250g paneer, cubed',
      '2 tbsp butter',
      '1 large onion, pureed',
      '1 tbsp ginger-garlic paste',
      '1.5 cups tomato puree',
      '1/2 cup cashews, soaked in hot water',
      '1 tsp chili powder',
      '1 tsp garam masala',
      '1/2 cup heavy cream',
      '1 tbsp dried fenugreek leaves (kasuri methi)',
      'Salt to taste'
    ],
    instructions: [
      'Blend the soaked cashews into a smooth paste.',
      'Heat butter in a pan over medium heat. Add the onion puree and ginger-garlic paste, and sauté until golden brown.',
      'Add the tomato puree and cook until the oil starts to separate from the masala.',
      'Stir in the cashew paste, chili powder, and garam masala. Cook for 2-3 minutes.',
      'Add 1 cup of water, salt, and bring to a simmer. Let it cook for 5-7 minutes.',
      'Add the paneer cubes and heavy cream. Simmer for another 2 minutes.',
      'Crush the dried fenugreek leaves between your palms and stir them into the curry.',
      'Serve hot with naan or rice.'
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '15g',
      carbohydrates: '20g',
      fat: '35g',
      fiber: '4g',
      sugar: '8g',
      sodium: '600mg'
    }
  },
  {
    id: 36,
    slug: 'vegetable-korma',
    title: 'Vegetable Korma',
    category: 'Dinner',
    cuisine: 'Indian',
    diet: 'veg',
    image: '/images/recipes/vegetable-korma.jpg',
    imageHint: 'vegetable curry',
    description: 'A rich and creamy mixed vegetable curry made with a blend of yogurt, coconut, and spices. A delightfully mild yet flavorful vegetarian dish.',
    prepTime: '20 mins',
    cookTime: '25 mins',
    servings: '4 people',
    ingredients: [
      '2 cups mixed vegetables (carrots, peas, beans, potatoes)',
      '1 tbsp oil',
      '1 onion, finely chopped',
      '1 tbsp ginger-garlic paste',
      '1/2 cup yogurt',
      '1/2 cup coconut milk',
      '1/4 cup cashew paste',
      '1 tsp coriander powder',
      '1/2 tsp turmeric powder',
      '1/2 tsp garam masala',
      'Salt to taste'
    ],
    instructions: [
      'Chop and boil the mixed vegetables until they are tender. Drain and set aside.',
      'Heat oil in a pan, add the chopped onion and sauté until translucent.',
      'Add ginger-garlic paste and sauté for another minute.',
      'Lower the heat and add the yogurt, stirring continuously to prevent curdling.',
      'Add the coconut milk, cashew paste, coriander powder, turmeric powder, and salt. Mix well.',
      'Add the boiled vegetables to the gravy and simmer for 5-7 minutes.',
      'Sprinkle with garam masala and stir gently.',
      'Serve hot with flatbread or rice.'
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '10g',
      carbohydrates: '30g',
      fat: '25g',
      fiber: '8g',
      sugar: '10g',
      sodium: '550mg'
    }
  },
  {
    id: 37,
    slug: 'lamb-rogan-josh',
    title: 'Lamb Rogan Josh',
    category: 'Dinner',
    cuisine: 'Indian',
    diet: 'non-veg',
    image: '/images/recipes/lamb-rogan-josh.jpg',
    imageHint: 'lamb curry',
    description: 'A fragrant and robust lamb curry from Kashmir, known for its brilliant red color from Kashmiri chilies and aromatic spices.',
    prepTime: '20 mins',
    cookTime: '1 hr 30 mins',
    servings: '4 people',
    ingredients: [
      '2 lbs lamb shoulder, cut into cubes',
      '1/2 cup plain yogurt',
      '4 tbsp vegetable oil',
      '1 large onion, thinly sliced',
      '1 tbsp ginger-garlic paste',
      '2 tsp Kashmiri red chili powder',
      '1 tsp turmeric powder',
      '2 tsp ground coriander',
      '1 tsp ground cumin',
      '1 tsp garam masala',
      'Salt to taste'
    ],
    instructions: [
      'In a bowl, marinate the lamb cubes with yogurt and a pinch of salt for at least 30 minutes.',
      'Heat oil in a heavy-bottomed pot. Add the sliced onions and fry until golden brown.',
      'Add the ginger-garlic paste and sauté for a minute.',
      'Add all the powdered spices (Kashmiri chili, turmeric, coriander, cumin) and fry for another minute.',
      'Add the marinated lamb and brown it on all sides.',
      'Pour in 2 cups of hot water, bring to a boil, then reduce the heat to low. Cover and simmer for 1 to 1.5 hours, or until the lamb is tender.',
      'Stir in the garam masala and cook for a final 5 minutes.',
      'Serve hot, garnished with fresh cilantro.'
    ],
    nutrition: {
      calories: '600 kcal',
      protein: '50g',
      carbohydrates: '15g',
      fat: '40g',
      fiber: '4g',
      sugar: '6g',
      sodium: '800mg'
    }
  },
  {
    id: 38,
    slug: 'seared-scallops-lemon-butter',
    title: 'Seared Scallops with Lemon Butter',
    category: 'Dinner',
    cuisine: 'French',
    diet: 'non-veg',
    image: '/images/recipes/seared-scallops.jpg',
    imageHint: 'seared scallops',
    description: 'Perfectly seared scallops with a golden crust, finished in a simple yet elegant lemon butter sauce. A gourmet meal in minutes.',
    prepTime: '10 mins',
    cookTime: '5 mins',
    servings: '2 people',
    ingredients: [
      '1 lb large sea scallops, patted dry',
      '2 tbsp olive oil',
      '3 tbsp unsalted butter',
      '2 cloves garlic, minced',
      '1/4 cup dry white wine or chicken broth',
      'Juice of 1/2 lemon',
      '2 tbsp chopped fresh parsley',
      'Salt and pepper to taste'
    ],
    instructions: [
      'Season the dry scallops on both sides with salt and pepper.',
      'Heat olive oil in a large skillet over high heat until it shimmers.',
      'Carefully place the scallops in the hot skillet in a single layer, ensuring they don’t touch.',
      'Sear for 1.5-2 minutes on one side without moving them, until a golden-brown crust forms.',
      'Flip the scallops and add the butter to the pan. As it melts, add the garlic and cook for 1 minute.',
      'Pour in the wine to deglaze the pan. Let it bubble for 30 seconds.',
      'Remove from heat, stir in the lemon juice and parsley. Spoon the sauce over the scallops.',
      'Serve immediately.'
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '35g',
      carbohydrates: '8g',
      fat: '28g',
      fiber: '1g',
      sugar: '2g',
      sodium: '750mg'
    }
  }
];

export const getRecipeBySlug = (slug: string) => {
  return recipes.find(recipe => recipe.slug === slug);
}
